// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SsoConfigInitParameters struct {

	// User-facing label shown on the `/login` SSO button. Defaults to "Single Sign-On".
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Email domains routed to this Organization's SSO at sign-in time. Example: `["acme.com", "acme.co.uk"]`.
	EnforcedForDomains []*string `json:"enforcedForDomains,omitempty" tf:"enforced_for_domains,omitempty"`

	// When `true`, members of this Organization cannot sign in with email + password. They must use SSO. Test the flow end-to-end before flipping.
	IsRequired *bool `json:"isRequired,omitempty" tf:"is_required,omitempty"`

	// IdP's OAuth 2.0 authorization endpoint (e.g. `https://auth.example.com/oauth/v2/authorize`).
	OidcAuthorizationEndpoint *string `json:"oidcAuthorizationEndpoint,omitempty" tf:"oidc_authorization_endpoint,omitempty"`

	// OIDC `client_id` issued by your IdP for this OpenPanel install.
	OidcClientID *string `json:"oidcClientId,omitempty" tf:"oidc_client_id,omitempty"`

	// OIDC `client_secret`. Cleartext crosses TLS once on write, encrypted at rest server-side, and NEVER returned on read.
	OidcClientSecretSecretRef v1.LocalSecretKeySelector `json:"oidcClientSecretSecretRef" tf:"-"`

	// Optional JWKS endpoint for ID-token signature verification.
	OidcJwksURI *string `json:"oidcJwksUri,omitempty" tf:"oidc_jwks_uri,omitempty"`

	// IdP's OAuth 2.0 token endpoint (e.g. `https://auth.example.com/oauth/v2/token`).
	OidcTokenEndpoint *string `json:"oidcTokenEndpoint,omitempty" tf:"oidc_token_endpoint,omitempty"`

	// ID of the OpenPanel Organization this SSO config belongs to. Immutable after create.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-openpanel/apis/namespaced/organization/v1alpha1.Organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in organization to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v1.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in organization to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v1.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`

	// SSO provider type. Only `OIDC` is supported in v1.)
	ProviderType *string `json:"providerType,omitempty" tf:"provider_type,omitempty"`
}

type SsoConfigObservation struct {
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// User-facing label shown on the `/login` SSO button. Defaults to "Single Sign-On".
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Email domains routed to this Organization's SSO at sign-in time. Example: `["acme.com", "acme.co.uk"]`.
	EnforcedForDomains []*string `json:"enforcedForDomains,omitempty" tf:"enforced_for_domains,omitempty"`

	// Reported by the server on every read — `true` once a secret has been written. Useful for catching drift when an out-of-band edit clears the secret.
	HasOidcClientSecret *bool `json:"hasOidcClientSecret,omitempty" tf:"has_oidc_client_secret,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// When `true`, members of this Organization cannot sign in with email + password. They must use SSO. Test the flow end-to-end before flipping.
	IsRequired *bool `json:"isRequired,omitempty" tf:"is_required,omitempty"`

	// IdP's OAuth 2.0 authorization endpoint (e.g. `https://auth.example.com/oauth/v2/authorize`).
	OidcAuthorizationEndpoint *string `json:"oidcAuthorizationEndpoint,omitempty" tf:"oidc_authorization_endpoint,omitempty"`

	// OIDC `client_id` issued by your IdP for this OpenPanel install.
	OidcClientID *string `json:"oidcClientId,omitempty" tf:"oidc_client_id,omitempty"`

	// Optional JWKS endpoint for ID-token signature verification.
	OidcJwksURI *string `json:"oidcJwksUri,omitempty" tf:"oidc_jwks_uri,omitempty"`

	// IdP's OAuth 2.0 token endpoint (e.g. `https://auth.example.com/oauth/v2/token`).
	OidcTokenEndpoint *string `json:"oidcTokenEndpoint,omitempty" tf:"oidc_token_endpoint,omitempty"`

	// ID of the OpenPanel Organization this SSO config belongs to. Immutable after create.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// SSO provider type. Only `OIDC` is supported in v1.)
	ProviderType *string `json:"providerType,omitempty" tf:"provider_type,omitempty"`

	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type SsoConfigParameters struct {

	// User-facing label shown on the `/login` SSO button. Defaults to "Single Sign-On".
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Email domains routed to this Organization's SSO at sign-in time. Example: `["acme.com", "acme.co.uk"]`.
	// +kubebuilder:validation:Optional
	EnforcedForDomains []*string `json:"enforcedForDomains,omitempty" tf:"enforced_for_domains,omitempty"`

	// When `true`, members of this Organization cannot sign in with email + password. They must use SSO. Test the flow end-to-end before flipping.
	// +kubebuilder:validation:Optional
	IsRequired *bool `json:"isRequired,omitempty" tf:"is_required,omitempty"`

	// IdP's OAuth 2.0 authorization endpoint (e.g. `https://auth.example.com/oauth/v2/authorize`).
	// +kubebuilder:validation:Optional
	OidcAuthorizationEndpoint *string `json:"oidcAuthorizationEndpoint,omitempty" tf:"oidc_authorization_endpoint,omitempty"`

	// OIDC `client_id` issued by your IdP for this OpenPanel install.
	// +kubebuilder:validation:Optional
	OidcClientID *string `json:"oidcClientId,omitempty" tf:"oidc_client_id,omitempty"`

	// OIDC `client_secret`. Cleartext crosses TLS once on write, encrypted at rest server-side, and NEVER returned on read.
	// +kubebuilder:validation:Optional
	OidcClientSecretSecretRef v1.LocalSecretKeySelector `json:"oidcClientSecretSecretRef" tf:"-"`

	// Optional JWKS endpoint for ID-token signature verification.
	// +kubebuilder:validation:Optional
	OidcJwksURI *string `json:"oidcJwksUri,omitempty" tf:"oidc_jwks_uri,omitempty"`

	// IdP's OAuth 2.0 token endpoint (e.g. `https://auth.example.com/oauth/v2/token`).
	// +kubebuilder:validation:Optional
	OidcTokenEndpoint *string `json:"oidcTokenEndpoint,omitempty" tf:"oidc_token_endpoint,omitempty"`

	// ID of the OpenPanel Organization this SSO config belongs to. Immutable after create.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-openpanel/apis/namespaced/organization/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in organization to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDRef *v1.NamespacedReference `json:"organizationIdRef,omitempty" tf:"-"`

	// Selector for a Organization in organization to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v1.NamespacedSelector `json:"organizationIdSelector,omitempty" tf:"-"`

	// SSO provider type. Only `OIDC` is supported in v1.)
	// +kubebuilder:validation:Optional
	ProviderType *string `json:"providerType,omitempty" tf:"provider_type,omitempty"`
}

// SsoConfigSpec defines the desired state of SsoConfig
type SsoConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SsoConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SsoConfigInitParameters `json:"initProvider,omitempty"`
}

// SsoConfigStatus defines the observed state of SsoConfig.
type SsoConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SsoConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SsoConfig is the Schema for the SsoConfigs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,openpanel}
type SsoConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oidcAuthorizationEndpoint) || (has(self.initProvider) && has(self.initProvider.oidcAuthorizationEndpoint))",message="spec.forProvider.oidcAuthorizationEndpoint is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oidcClientId) || (has(self.initProvider) && has(self.initProvider.oidcClientId))",message="spec.forProvider.oidcClientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oidcClientSecretSecretRef)",message="spec.forProvider.oidcClientSecretSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oidcTokenEndpoint) || (has(self.initProvider) && has(self.initProvider.oidcTokenEndpoint))",message="spec.forProvider.oidcTokenEndpoint is a required parameter"
	Spec   SsoConfigSpec   `json:"spec"`
	Status SsoConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SsoConfigList contains a list of SsoConfigs
type SsoConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SsoConfig `json:"items"`
}

// Repository type metadata.
var (
	SsoConfig_Kind             = "SsoConfig"
	SsoConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SsoConfig_Kind}.String()
	SsoConfig_KindAPIVersion   = SsoConfig_Kind + "." + CRDGroupVersion.String()
	SsoConfig_GroupVersionKind = CRDGroupVersion.WithKind(SsoConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&SsoConfig{}, &SsoConfigList{})
}
