// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClientInitParameters struct {

	// (List of String) List of allowed origins (write clients only).
	// List of allowed origins (write clients only).
	Cors []*string `json:"cors,omitempty" tf:"cors,omitempty"`

	// readable name shown in the OpenPanel dashboard.
	// Human-readable name shown in the OpenPanel dashboard.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Owning Project ID. Required.
	// Owning Project ID. Required.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-openpanel/apis/cluster/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) One of read, write, root. Drives which API surfaces accept this Client. Immutable after create.
	// One of `read`, `write`, `root`. Drives which API surfaces accept this Client. Immutable after create.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ClientObservation struct {

	// (List of String) List of allowed origins (write clients only).
	// List of allowed origins (write clients only).
	Cors []*string `json:"cors,omitempty" tf:"cors,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// client-id header value.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// readable name shown in the OpenPanel dashboard.
	// Human-readable name shown in the OpenPanel dashboard.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Owning Project ID. Required.
	// Owning Project ID. Required.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) One of read, write, root. Drives which API surfaces accept this Client. Immutable after create.
	// One of `read`, `write`, `root`. Drives which API surfaces accept this Client. Immutable after create.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ClientParameters struct {

	// (List of String) List of allowed origins (write clients only).
	// List of allowed origins (write clients only).
	// +kubebuilder:validation:Optional
	Cors []*string `json:"cors,omitempty" tf:"cors,omitempty"`

	// readable name shown in the OpenPanel dashboard.
	// Human-readable name shown in the OpenPanel dashboard.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Owning Project ID. Required.
	// Owning Project ID. Required.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-openpanel/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) One of read, write, root. Drives which API surfaces accept this Client. Immutable after create.
	// One of `read`, `write`, `root`. Drives which API surfaces accept this Client. Immutable after create.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ClientSpec defines the desired state of Client
type ClientSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClientParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClientInitParameters `json:"initProvider,omitempty"`
}

// ClientStatus defines the observed state of Client.
type ClientStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClientObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Client is the Schema for the Clients API. An OpenPanel SDK credential (Client). type=write is what your front-end SDK ships with; type=read reads analytics out via the API; type=root can call /manage. The secret is returned only on create.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,openpanel}
type Client struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ClientSpec   `json:"spec"`
	Status ClientStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClientList contains a list of Clients
type ClientList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Client `json:"items"`
}

// Repository type metadata.
var (
	Client_Kind             = "Client"
	Client_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Client_Kind}.String()
	Client_KindAPIVersion   = Client_Kind + "." + CRDGroupVersion.String()
	Client_GroupVersionKind = CRDGroupVersion.WithKind(Client_Kind)
)

func init() {
	SchemeBuilder.Register(&Client{}, &ClientList{})
}
