// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ReferenceInitParameters struct {

	// (String) RFC 3339 timestamp the reference annotates.
	// RFC 3339 timestamp the reference annotates.
	Date *string `json:"date,omitempty" tf:"date,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Owning Project ID.
	// Owning Project ID.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-upjet-openpanel/apis/cluster/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String)
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ReferenceObservation struct {

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) RFC 3339 timestamp the reference annotates.
	// RFC 3339 timestamp the reference annotates.
	Date *string `json:"date,omitempty" tf:"date,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Owning Project ID.
	// Owning Project ID.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String)
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ReferenceParameters struct {

	// (String) RFC 3339 timestamp the reference annotates.
	// RFC 3339 timestamp the reference annotates.
	// +kubebuilder:validation:Optional
	Date *string `json:"date,omitempty" tf:"date,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Owning Project ID.
	// Owning Project ID.
	// +crossplane:generate:reference:type=github.com/hops-ops/provider-upjet-openpanel/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

// ReferenceSpec defines the desired state of Reference
type ReferenceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ReferenceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReferenceInitParameters `json:"initProvider,omitempty"`
}

// ReferenceStatus defines the observed state of Reference.
type ReferenceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ReferenceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Reference is the Schema for the References API. A Reference annotates an event in the OpenPanel timeline (deploy, campaign, incident). Surfaces on dashboards alongside the analytics.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,openpanel}
type Reference struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.date) || (has(self.initProvider) && has(self.initProvider.date))",message="spec.forProvider.date is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	Spec   ReferenceSpec   `json:"spec"`
	Status ReferenceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReferenceList contains a list of References
type ReferenceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Reference `json:"items"`
}

// Repository type metadata.
var (
	Reference_Kind             = "Reference"
	Reference_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Reference_Kind}.String()
	Reference_KindAPIVersion   = Reference_Kind + "." + CRDGroupVersion.String()
	Reference_GroupVersionKind = CRDGroupVersion.WithKind(Reference_Kind)
)

func init() {
	SchemeBuilder.Register(&Reference{}, &ReferenceList{})
}
